version: '3.4'

services:

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: iproj-backend-container
    image: iproj-backend-image:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - 5001:8080
      - 4343:443

  